services:
- type: web
  name: paper-trader
  runtime: python
  repo: https://github.com/hayleypyle/paper-trader-6
  plan: starter
  envVars:
  - key: DATABASE_URL
    sync: false
  - key: PYTHON_VERSION
    sync: false
  region: ohio
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn website.wsgi:application
  preDeployCommand: python manage.py collectstatic --no-input python manage.py migrate
version: "1"
