# Generated by Django 5.0.4 on 2024-04-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_name', models.CharField(max_length=50)),
                ('share_quantity', models.IntegerField(default=0)),
                ('shares_owned', models.IntegerField(default=0)),
                ('total_price', models.IntegerField(default=0)),
                ('share_price', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=10000)),
            ],
        ),
    ]
